-->Log statments from run_kubernetes.sh window (after running make_prediction.sh):
Error from server (AlreadyExists): pods "flaskprediction" already exists
NAME              READY   STATUS    RESTARTS   AGE
flaskprediction   1/1     Running   0          38s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000

+++ Logs from make_predictions.sh window:
Port: 8000
{
  "prediction": [
    20.35373177134412
  ]
}

+++ Logs from inside the container running in kubernetes (kubectl logs flaskprediction):
* Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-548-227
[2021-06-25 03:27:04,891] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2021-06-25 03:27:04,915] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-06-25 03:27:04,920] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-06-25 03:27:04,931] INFO in app: Output prediction:
[20.35373177134412]
127.0.0.1 - - [25/Jun/2021 03:27:04] "POST /predict HTTP/1.1" 200 -

